services:

  mongo:
    image: mongo:latest
    container_name: employee_activity_monitoring_mongo_container
    restart: always
    ports:
      - "27017:27017"
    networks:
      - employee
  backend_service:
    build: ./backend
    container_name: employee_activity_monitoring_backend_container
    restart: always
    env_file:
      - ./backend/.env
    ports:
        - "4000:4000"
    networks:
      - employee


  client_service:
    build: ./client
    container_name: employee_activity_monitoring_client_container
    args:
      - VITE_API_URL=http://localhost:10.51.226.253
    restart: always
    env_file:
      - ./client/.env
    ports:
      - "5173:5173"
    depends_on:
      - backend_service
    networks:
      - employee

  # nginx:
  #   image: nginx:alpine
  #   container_name: employee-activity-monitering
  #   restart: unless-stopped
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     -  client_service
  #     -  backend_service
  #   networks:
  #     - employee


networks:
    employee:
      driver: bridge