# simple implement the reverese proxy 
# to serve the client using this /
# to serve the server by using this /api/*

events{}

http{

    client_max_body_size 10M;

    server{
        listen 80;

        location /{
            proxy_pass http://employee_activity_monitoring_client_container:5173;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forward-Proto $scheme;
            proxy_buffering off;

        }
        location /api {
            proxy_pass http://employee_activity_monitoring_backend_container:4000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_buffering off;
            proxy_connect_timeout 5s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;
        }

       location = /nginx-health {
            return 200 "ok";
            add_header Content-type text/plain;
        }
    }
}